name: Appstream

on:
  push:
    branches: [ main, appstream ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Generate AppStream files
      run: |
        for entry in "metadata"/*
        do
          go run generate-appstream.go --input="$entry"
        done
